name: Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        config:
          - {
            name: "Clang",
            build_type: "Release",
            cc: "clang",
            cxx: "clang++",
            generators: "Ninja",
            architecture: ""
          }

    steps:
      - uses: actions/checkout@v2

      - name: Install ninja
        run: |
          sudo apt install ninja-build
          ninja --version

      - name: Configure CMake
        run: |
          cmake -B ${{ github.workspace }}/build -G "${{ matrix.config.generators }}" -DBUILD_SHARED_LIBS=OFF -DCMAKE_CXX_FLAGS=-stdlib=libc++ -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} -DCXX_STANDARD=C++20

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{ matrix.config.build_type }} --target FlowMesh

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{ matrix.config.build_type }}
