name: Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        config:
          - {
            name: "Clang",
            build_type: "Release",
            cc: "clang",
            cxx: "clang++",
            generators: "Ninja",
            architecture: ""
          }

    steps:
      - uses: actions/checkout@v2

      - name: Install ninja
        run: |
          sudo apt install ninja-build
          ninja --version

      - name: Install clang
        run: |
          sudo apt install clang
          clang++ --version

      - name: Install filament deps
        run : |
          sudo apt install libglu1-mesa-dev
          sudo apt install libxi-dev
          sudo apt install libxxf86vm-dev

      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/build -G "${{ matrix.config.generators }}" -DBUILD_SHARED_LIBS=OFF -DCMAKE_CXX_FLAGS=-stdlib=libc++ -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} -DCMAKE_CXX_STANDARD=20
        shell: bash
        env:
            CC: clang-10
            CXX: clang++-10

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{ matrix.config.build_type }} --target MeshlerApp

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{ matrix.config.build_type }}
